language: java

stages:
  - mavenclean
  - pushondocker

jobs:
  include:
    - stage: mavenclean
      name: mavenclean
      script: mvn clean verify --file ./simple-api/pom.xml org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cecilekey
      if: branch = dev

    - stage: pushondocker
      name: docker
      script:
        - docker login -u $DOCKER_USER -p $DOCKER_PWD
        - docker build -t $DOCKER_USER/devopstp_2:database database
        - docker build -t $DOCKER_USER/devopstp_2:httpd httpd
        - docker build -t $DOCKER_USER/devopstp_2:simple-api simple-api
        - docker build -t $DOCKER_USER/devopstp_2:frontend frontend
        - docker push $DOCKER_USER/devopstp_2:database
        - docker push $DOCKER_USER/devopstp_2:httpd
        - docker push $DOCKER_USER/devopstp_2:simple-api
        - docker push $DOCKER_USER/devopstp_2:frontend
      if: branch = dev

cache:
  directories:
    - $HOME/.m2

services:
  - docker

addons:
  sonarcloud:
    organization: "devopsorgacecile"
    token: $SONARCLOUD_TOKEN
