language: java
script:
  - mvn clean verify --file ./simple-api/pom.xml

  # Connexion à Docker
  - docker login -u $DOCKER_USER -p $DOCKER_PWD

  # Build
  - docker build -t $DOCKER_USER/devopstp_2:database database
  - docker build -t $DOCKER_USER/devopstp_2:httpd httpd
  - docker build -t $DOCKER_USER/devopstp_2:simple-api simple-api

  # Publication des images
  - docker push $DOCKER_USER/devopstp_2:database
  - docker push $DOCKER_USER/devopstp_2:httpd
  - docker push $DOCKER_USER/devopstp_2:simple-api

cache:
  directories:
    - $HOME/.m2

services:
  - docker
