language: java
script:
  

  # Connexion à Docker
  - docker login -u $DOCKER_USER -p $DOCKER_PWD

  # Build
  - docker build -t $DOCKER_USER/devopstp_2:database database
  - docker build -t $DOCKER_USER/devopstp_2:httpd httpd
  - docker build -t $DOCKER_USER/devopstp_2:simple-api simple-api

  # Publication des images
  - docker push $DOCKER_USER/devopstp_2:database
  - docker push $DOCKER_USER/devopstp_2:httpd
  - docker push $DOCKER_USER/devopstp_2:simple-api

  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=CVhp_TP2Docker --file ./simple-api/pom.xml

addons:
  sonarcloud:
    organization: "cvhp"
    token:
      secure: "$SONARCLOUD_TOKEN"

cache:
  directories:
    - $HOME/.m2

services:
  - docker
