- name: Launch app
  docker_container:
    name: backend
    image: cecile98/devopstp_2:simple-api
    state: started
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_PASSWORD: "{{ db_password }}"
      SPRING_DATASOURCE_USER: "{{ db_user }}"
      SPRING_DATASOURCE_URL: jbdc:postgresql://database:5432/db